name       : libtiff
version    : 4.0.10
release    : 31
source     :
    - git|https://gitlab.com/libtiff/libtiff.git : c22f319eb4da5d75a5fcda41cf24983f7355d9c6
license    : libtiff
component  : desktop.library
summary    : Library for accessing TIFF files
description: |
    The LibTIFF package contains the TIFF libraries and associated utilities. The libraries are used by many programs for reading and writing TIFF files and the utilities are used for general work with TIFF files.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(liblzma)
    - pkgconfig32(libturbojpeg)
    - pkgconfig32(libzstd)
    - pkgconfig32(zlib)
patterns   :
    - devel : /usr/share/man/man3
    - docs : /usr/share/doc
    - utils : /usr/bin
    - utils : /usr/share/man/man1
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
