name        : libtiff
version     : 4.0.3
release     : 8
source      :
    - http://download.osgeo.org/libtiff/tiff-4.0.3.tar.gz : ea1aebe282319537fb2d4d7805f478dd4e0e05c33d0928baba76a7c963684872
license     :
    - libtiff
summary     : Library for accessing TIFF files
builddeps   :
    - pkgconfig(liblzma)
    - libjpeg-turbo-32bit-devel
    - libgcc-32bit
    - glibc-32bit-devel
    - libstdc++-32bit
description : |
    The LibTIFF package contains the TIFF libraries and associated utilities. The libraries are used by many programs for reading and writing TIFF files and the utilities are used for general work with TIFF files.
emul32     : yes
patterns   :
    - devel: /usr/share/man/man3
    - docs: /usr/share/doc
    - utils: /usr/bin
    - utils: /usr/share/man/man1
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2013-1960.patch
    %patch -p1 < $pkgfiles/security/cve-2013-1961.patch
    %patch -p1 < $pkgfiles/security/cve-2013-4232.patch
    %patch -p1 < $pkgfiles/security/cve-2013-4243.patch
    %patch -p1 < $pkgfiles/security/cve-2013-4244.patch
    %patch -p1 < $pkgfiles/security/cve-2014-9330.patch
    %configure --prefix=/usr \
               --disable-jbig \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
