name        : libtiff
version     : 4.0.6
release     : 10
source     :
    - http://download.osgeo.org/libtiff/tiff-4.0.6.tar.gz : 4d57a50907b510e3049a4bba0d7888930fdfc16ce49f1bf693e5b6247370d68c
license     :
    - libtiff
summary     : Library for accessing TIFF files
builddeps   :
    - pkgconfig(liblzma)
    - libjpeg-turbo-32bit-devel
    - libgcc-32bit
    - glibc-32bit-devel
    - libstdc++-32bit
description : |
    The LibTIFF package contains the TIFF libraries and associated utilities. The libraries are used by many programs for reading and writing TIFF files and the utilities are used for general work with TIFF files.
emul32     : yes
optimize   : speed
patterns   :
    - devel: /usr/share/man/man3
    - docs: /usr/share/doc
    - utils: /usr/bin
    - utils: /usr/share/man/man1
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2015-7554.patch
    %configure --prefix=/usr \
               --disable-jbig \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
