name       : libtiff
version    : 4.0.7
release    : 17
source     :
    - http://download.osgeo.org/libtiff/tiff-4.0.7.tar.gz : 9f43a2cfb9589e5cecaa66e16bf87f814c945f22df7ba600d63aac4632c4f019
license    :
    - libtiff
component  : desktop.library
summary    : Library for accessing TIFF files
description: |
    The LibTIFF package contains the TIFF libraries and associated utilities. The libraries are used by many programs for reading and writing TIFF files and the utilities are used for general work with TIFF files.
emul32     : yes
builddeps  :
    - pkgconfig(liblzma)
    - libjpeg-turbo-32bit-devel
    - libgcc-32bit
    - glibc-32bit-devel
    - libstdc++-32bit
optimize   : speed
patterns   :
    - devel : /usr/share/man/man3
    - docs : /usr/share/doc
    - utils : /usr/bin
    - utils : /usr/share/man/man1
setup      : |
    %apply_patches
    %configure --prefix=/usr \
               --disable-jbig \
               --disable-static
build      : |
    %make
install    : |
    %make_install
